import styles from '../styles/About.module.css'
import data from '../data/employees.json'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useState } from  'react'
import Card from '../components/Cards'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })
import Navbar from '../components/NavBar'


export default function About() {

    console.log(data)
      const [information, setInformation]=useState([...data])

    return(
     
    <>
    <Head>
        <title>The Dream Team </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar></Navbar>

      <main className={styles.main}>

        <header>
         <h2> Meet the SPEED Team! </h2>


           </header>
        
      
      <div class = "container">

     
     
    {
      information && information.map((info, index)=> {
        {
          return (
             <div class ="employee__container">
            <Card 
            key={index} 
            name={info.firstName} 
            job={info.position}
            degree={info.degree}
            colour= "blue"
            font= "32px"
          
           
            />
            
            </div>
          )
        }
      })
    }
</div>
         

    </main>
  </>
)
}

        