import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css' 
import Card from '../components/Cards'
import data from '../data/education.json'
import Link from 'next/link'
import { useState } from  'react'
import Navbar from '../components/NavBar'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  console.log(data)

  const [information, setInformation]=useState([...data])

  return (
    <>
      <Head>
        <title>The Dream Team </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar></Navbar>

      <main className={styles.main}>

        <header>
         
           </header>
        
      {
        information && information.map((info, index)=> {
          if(info.department.toLowerCase() === "business") {
            return (
              <Card key={index} degree={info.degree} colour="blue" font="50px" />
            )
          }
        })
      }

      {
        information && information.map((info, index)=> {
          if(info.department.toLowerCase() === "computing") {
            return (
              <Card key={index} degree ={info.degree} colour="blue" font="50px" />
            )
          }
        }) 
      }      
      </main>
    </>
  )
}
